lib/solar_guitar_store_web/router.ex
defmodule SolarGuitarStoreWeb.Router do
  use SolarGuitarStoreWeb, :router

  import SolarGuitarStoreWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :authenticated do
    plug SolarGuitarStoreWeb.GuardianAuthPipeline
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SolarGuitarStoreWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/api/v1", SolarGuitarStoreWeb.Api.V1 do
    pipe_through [:api]
    post "/session", SessionController, :create
  end

  scope "/api/v1", SolarGuitarStoreWeb.Api.V1 do
    pipe_through [:api, :authenticated]
    get "/guitars", GuitarController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", SolarGuitarStoreWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: SolarGuitarStoreWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", SolarGuitarStoreWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", SolarGuitarStoreWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", SolarGuitarStoreWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/solar_guitar_store_web/controllers/user_reset_password_controller.ex
defmodule SolarGuitarStoreWeb.UserResetPasswordController do
  use SolarGuitarStoreWeb, :controller

  alias SolarGuitarStore.Accounts

  plug :get_user_by_reset_password_token when action in [:edit, :update]

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"user" => %{"email" => email}}) do
    if user = Accounts.get_user_by_email(email) do
      Accounts.deliver_user_reset_password_instructions(
        user,
        &Routes.user_reset_password_url(conn, :edit, &1)
      )
    end

    # Regardless of the outcome, show an impartial success/error message.
    conn
    |> put_flash(
      :info,
      "If your email is in our system, you will receive instructions to reset your password shortly."
    )
    |> redirect(to: "/")
  end

  def edit(conn, _params) do
    render(conn, "edit.html", changeset: Accounts.change_user_password(conn.assigns.user))
  end

  # Do not log in the user after reset password to avoid a
  # leaked token giving the user access to the account.
  def update(conn, %{"user" => user_params}) do
    case Accounts.reset_user_password(conn.assigns.user, user_params) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Password reset successfully.")
        |> redirect(to: Routes.user_session_path(conn, :new))

      {:error, changeset} ->
        render(conn, "edit.html", changeset: changeset)
    end
  end

  defp get_user_by_reset_password_token(conn, _opts) do
    %{"token" => token} = conn.params

    if user = Accounts.get_user_by_reset_password_token(token) do
      conn |> assign(:user, user) |> assign(:token, token)
    else
      conn
      |> put_flash(:error, "Reset password link is invalid or it has expired.")
      |> redirect(to: "/")
      |> halt()
    end
  end
end

lib/solar_guitar_store_web/views/user_reset_password_view.ex
defmodule SolarGuitarStoreWeb.UserResetPasswordView do
  use SolarGuitarStoreWeb, :view
end

lib/solar_guitar_store_web/templates/user_reset_password/edit.html.eex
<h1>Reset password</h1>

<%= form_for @changeset, Routes.user_reset_password_path(@conn, :update, @token), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :password, "New password" %>
  <%= password_input f, :password, required: true %>
  <%= error_tag f, :password %>

  <%= label f, :password_confirmation, "Confirm new password" %>
  <%= password_input f, :password_confirmation, required: true %>
  <%= error_tag f, :password_confirmation %>

  <div>
    <%= submit "Reset password" %>
  </div>
<% end %>

<p>
  <%= link "Register", to: Routes.user_registration_path(@conn, :new) %> |
  <%= link "Log in", to: Routes.user_session_path(@conn, :new) %>
</p>

lib/solar_guitar_store_web/templates/user_reset_password/new.html.eex
<h1>Forgot your password?</h1>

<%= form_for :user, Routes.user_reset_password_path(@conn, :create), fn f -> %>
  <%= label f, :email %>
  <%= email_input f, :email, required: true %>

  <div>
    <%= submit "Send instructions to reset password" %>
  </div>
<% end %>

<p>
  <%= link "Register", to: Routes.user_registration_path(@conn, :new) %> |
  <%= link "Log in", to: Routes.user_session_path(@conn, :new) %>
</p>